name: RSpec

on:
  push:
    branches: [main]
  pull_request:
  workflow_call:

jobs:
  rspec:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Ruby 3.2
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.2.1
          bundler-cache: true
      - name: Run tests
        run: bundle exec rake spec
